/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCheckRouteImport } from './routes/api/public/check'
import { Route as ApiPublicStatusRouteImport } from './routes/api/public/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckRoute = ApiPublicCheckRouteImport.update({
  id: '/api/public/check',
  path: '/api/public/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStatusRoute = ApiPublicStatusRouteImport.update({
  id: '/api/public/status',
  path: '/api/public/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/check': typeof ApiPublicCheckRoute
  '/api/public/status': typeof ApiPublicStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/check': typeof ApiPublicCheckRoute
  '/api/public/status': typeof ApiPublicStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/check': typeof ApiPublicCheckRoute
  '/api/public/status': typeof ApiPublicStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/check' | '/api/public/status'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/check' | '/api/public/status'
  id: '__root__' | '/' | '/api/public/check' | '/api/public/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCheckRoute: typeof ApiPublicCheckRoute
  ApiPublicStatusRoute: typeof ApiPublicStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/check': {
      id: '/api/public/check'
      path: '/api/public/check'
      fullPath: '/api/public/check'
      preLoaderRoute: typeof ApiPublicCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/status': {
      id: '/api/public/status'
      path: '/api/public/status'
      fullPath: '/api/public/status'
      preLoaderRoute: typeof ApiPublicStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCheckRoute: ApiPublicCheckRoute,
  ApiPublicStatusRoute: ApiPublicStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
